In [1]:
import numpy as np
import matplotlib
import pandas as pd
import os

# Import Data

In [2]:
pwd

'C:\\Users\\Gagan\\Desktop\\carona'

In [3]:
df = pd.read_excel("carona_data.xlsx")

In [4]:
df

fever  body_pain  age  runny_nose  diff_breath  infection_problem
0       101          1   40           1           -1                  1
1        99          1   88           0           -1                  0
2       102          0    5           0            0                  0
3       101          1   73           1            1                  1
4       102          1   40           1            1                  1
...     ...        ...  ...         ...          ...                ...
2362     98          0   29           1            0                  1
2363    101          1   45           1            1                  0
2364    102          1   82           1           -1                  1
2365     99          0   45           1           -1                  1
2366     99          1   58           1            0                  1

[2367 rows x 6 columns]

In [5]:
df.head(5)

fever  body_pain  age  runny_nose  diff_breath  infection_problem
0    101          1   40           1           -1                  1
1     99          1   88           0           -1                  0
2    102          0    5           0            0                  0
3    101          1   73           1            1                  1
4    102          1   40           1            1                  1

In [6]:
df.tail()

fever  body_pain  age  runny_nose  diff_breath  infection_problem
2362     98          0   29           1            0                  1
2363    101          1   45           1            1                  0
2364    102          1   82           1           -1                  1
2365     99          0   45           1           -1                  1
2366     99          1   58           1            0                  1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2367 entries, 0 to 2366
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fever              2367 non-null   int64
 1   body_pain          2367 non-null   int64
 2   age                2367 non-null   int64
 3   runny_nose         2367 non-null   int64
 4   diff_breath        2367 non-null   int64
 5   infection_problem  2367 non-null   int64
dtypes: int64(6)
memory usage: 111.1 KB


In [8]:
df['diff_breath'].value_counts()

-1    811
 0    794
 1    762
Name: diff_breath, dtype: int64

In [9]:
df.describe()

fever    body_pain          age   runny_nose  diff_breath  \
count  2367.000000  2367.000000  2367.000000  2367.000000  2367.000000   
mean     99.990706     0.490072    45.465568     0.480355    -0.020701   
std       1.412688     0.500007    25.492337     0.499719     0.815111   
min      98.000000     0.000000     1.000000     0.000000    -1.000000   
25%      99.000000     0.000000    23.000000     0.000000    -1.000000   
50%     100.000000     0.000000    45.000000     0.000000     0.000000   
75%     101.000000     1.000000    68.000000     1.000000     1.000000   
max     102.000000     1.000000    90.000000     1.000000     1.000000   

       infection_problem  
count        2367.000000  
mean            0.504436  
std             0.500086  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             1.000000  
max             1.000000

# Train Test Split

In [10]:
import numpy as np

In [11]:
def data_split(data,ratio):
    np.random.seed(40)
    shuffle = np.random.permutation(len(data))
    test_size = int(len(data)*ratio)
    test_indices = shuffle[:test_size]
    train_indices = shuffle[test_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

    

In [12]:
np.random.permutation(7)

array([1, 2, 4, 0, 5, 6, 3])

In [13]:
train,test = data_split(df,0.2)

In [14]:
train

fever  body_pain  age  runny_nose  diff_breath  infection_problem
227      99          1   34           0            0                  0
2146     99          0   84           0            1                  0
1503    100          0   40           1            0                  0
997      98          0   60           1            1                  1
891      99          1   64           1            0                  0
...     ...        ...  ...         ...          ...                ...
1863    100          1   36           1            1                  1
1330    100          0   43           1            0                  0
2213    102          0   79           0            1                  1
2055    102          0   61           1           -1                  1
2267     99          1   34           0            0                  0

[1894 rows x 6 columns]

In [15]:
test

fever  body_pain  age  runny_nose  diff_breath  infection_problem
497     100          0   27           0           -1                  0
2207    101          0   54           1            0                  0
1482    101          1   90           0           -1                  1
1377     98          0   42           0           -1                  0
279      98          1   19           0            1                  1
...     ...        ...  ...         ...          ...                ...
364      99          1   27           1            1                  0
143      99          1   21           0            0                  1
976     100          1   70           1            1                  1
739      99          0   87           0            0                  1
554      99          1   81           0            0                  0

[473 rows x 6 columns]

In [16]:
x_train = train[['fever','body_pain','runny_nose','diff_breath']].to_numpy()
x_test = test[['fever','body_pain','runny_nose','diff_breath']].to_numpy()

In [17]:
x_train

array([[ 99,   1,   0,   0],
       [ 99,   0,   0,   1],
       [100,   0,   1,   0],
       ...,
       [102,   0,   0,   1],
       [102,   0,   1,  -1],
       [ 99,   1,   0,   0]], dtype=int64)

In [18]:
x_test

array([[100,   0,   0,  -1],
       [101,   0,   1,   0],
       [101,   1,   0,  -1],
       ...,
       [100,   1,   1,   1],
       [ 99,   0,   0,   0],
       [ 99,   1,   0,   0]], dtype=int64)

In [19]:
y_train = train[['infection_problem']].to_numpy().reshape(1894,)
y_test = test[['infection_problem']].to_numpy().reshape(473,)

In [20]:
y_train.reshape(1,-1)

array([[0, 0, 0, ..., 1, 1, 0]], dtype=int64)

In [21]:
y_test.reshape(1,-1)

array([[0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 

In [22]:
x_train

array([[ 99,   1,   0,   0],
       [ 99,   0,   0,   1],
       [100,   0,   1,   0],
       ...,
       [102,   0,   0,   1],
       [102,   0,   1,  -1],
       [ 99,   1,   0,   0]], dtype=int64)

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
input = [100,0,-1,0]
info_prob = clf.predict_proba([input])[0][1]

In [26]:
info_prob

0.5484440301798288